# docker compose yaml directing docker to modified config and data paths
services:
  pygeoapi:
    image: geopython/pygeoapi:latest

    container_name: pygeoapi

    ports:
      - 5000:80

    volumes:
      - ./pygeoapi-config.yml:/pygeoapi/local.config.yml
      - ./data:/data